name: Test
on:
  pull_request:
  push:
    branches:
        - main

jobs:

  build-and-test:
    name: Run Test Suite
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Test Image
      run: docker-compose build

    - name: Run Tests
      run: docker-compose run pyspark-sagemaker

  deploy-sagemaker-pipeline:
    needs: build-and-test
    name: Deploy SageMaker Pipeline
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Test Image
      run: docker-compose build

    - name: Deploy Pipeline
      run: |
        docker-compose run \
          -e AWS_ACCESS_KEY_ID="${{secrets.AWS_ACCESS_KEY_ID}}" \
          -e  AWS_SECRET_ACCESS_KEY="${{secrets.AWS_SECRET_ACCESS_KEY}}" \
          -e AWS_DEFAULT_REGION="eu-west-1" \
          pyspark-sagemaker python sagemaker_pipeline.py
